"""Added IoT models

Revision ID: 13083c76a3b5
Revises: b0330a75fea5
Create Date: 2026-09-11 19:53:32.210378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13083c76a3b5'
down_revision = 'b0330a75fea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footfalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('exit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('footfall', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_footfall_area_name'))
        batch_op.drop_index(batch_op.f('ix_footfall_device_id'))
        batch_op.drop_index(batch_op.f('ix_footfall_hourly_bucket'))
        batch_op.drop_index(batch_op.f('ix_footfall_timestamp'))

    op.drop_table('footfall')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=True))
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_alerts_category'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_read'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_source_device_id'))
        batch_op.drop_constraint(batch_op.f('alerts_source_device_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'])
        batch_op.drop_column('source_device_id')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolved_by')

    with op.batch_alter_table('camera_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_camera_events_camera_id_str'))
        batch_op.drop_index(batch_op.f('ix_camera_events_device_id'))
        batch_op.drop_index(batch_op.f('ix_camera_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_camera_events_timestamp'))
        batch_op.drop_column('snapshot_url')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('bbox_coordinates')
        batch_op.drop_column('camera_id_str')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_column('mac_address')
        batch_op.drop_column('firmware_version')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('config_meta')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_shelf_code'), ['shelf_code'], unique=False)

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mock', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_device_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_is_anomaly'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_sensor_id_str'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_timestamp'))
        batch_op.drop_column('sensor_id_str')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('location')
        batch_op.drop_column('is_anomaly')
        batch_op.drop_column('threshold_max')
        batch_op.drop_column('threshold_min')

    with op.batch_alter_table('shelf_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_shelf_statuses_device_id'))
        batch_op.drop_index(batch_op.f('ix_shelf_statuses_product_id'))
        batch_op.drop_index(batch_op.f('ix_shelf_statuses_section'))
        batch_op.drop_index(batch_op.f('ix_shelf_statuses_shelf_code'))
        batch_op.drop_index(batch_op.f('ix_shelf_statuses_status'))
        batch_op.drop_column('section')
        batch_op.drop_column('fill_percentage')
        batch_op.drop_column('capacity')
        batch_op.drop_column('shelf_code')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('current_stock_estimate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelf_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stock_estimate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shelf_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fill_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_shelf_statuses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_statuses_shelf_code'), ['shelf_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shelf_statuses_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_statuses_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_statuses_device_id'), ['device_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('confidence')
        batch_op.drop_column('estimated_quantity')

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('threshold_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_anomaly', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sensor_id_str', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_sensor_readings_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_sensor_id_str'), ['sensor_id_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_is_anomaly'), ['is_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_device_id'), ['device_id'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_mock')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_shelf_code'))
        batch_op.drop_column('shelf_code')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('config_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firmware_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('camera_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id_str', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bbox_coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('snapshot_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_camera_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_events_camera_id_str'), ['camera_id_str'], unique=False)
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source_device_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alerts_source_device_id_fkey'), 'devices', ['source_device_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_alerts_source_device_id'), ['source_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_category'), ['category'], unique=False)
        batch_op.alter_column('severity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('device_id')

    op.create_table('footfall',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_occupancy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dwell_time_avg_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hourly_bucket', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('footfall_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('footfall_pkey'))
    )
    with op.batch_alter_table('footfall', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_footfall_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_footfall_hourly_bucket'), ['hourly_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_footfall_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_footfall_area_name'), ['area_name'], unique=False)

    op.drop_table('footfalls')
    # ### end Alembic commands ###
